---
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/elucri/config/sonarr:/config
      - /home/elucri/Downloads/Torrents/Tv shows:/tv
      - /home/elucri/Downloads/Torrents/Transmission:/downloads
    ports:
      - 52000:8989
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/elucri/config/prowlarr:/config
    ports:
      - 52001:9696
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/elucri/config/bazarr:/config
      - /home/elucri/Downloads/Torrents/Movies:/movies
      - /home/elucri/Downloads/Torrents/Tv shows:/tv
    ports:
      - 52002:6767
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/elucri/config/radarr:/config
      - /home/elucri/Downloads/Torrents/Movies:/movies
      - /home/elucri/Downloads/Torrents/Transmission:/downloads
    ports:
      - 52003:7878
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - HOST_WHITELIST= #optional
    volumes:
      - /home/elucri/config/transmission:/config
      - /home/elucri/Downloads/Torrents/Transmission:/downloads
      - /home/elucri/Downloads/Torrents/Watch:/watch
    ports:
      - 52004:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/elucri/config/overseerr:/config
    ports:
      - 52005:5055
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    command: tunnel --no-autoupdate run --token ${CLOUDFLARED_TOKEN}
    restart: unless-stopped
    env_file:
      - .env

